image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.html public/
    - cp -r resources public/
    - cp -r .well-known public/
  artifacts:
    paths:
    - public
  only:
  - master
